### ISSUE TITLE
MS2 Review - Use Cases

### ISSUE THREAD

**Issue by webbja15** [F18MIS4173Team5/Team5#43]
Missing a trigger and can be more detailed on some of them. If a user is inputting information, the arrows should be pointing into the system (to the left). If the system is sending messages to the user, the arrows should be pointing out of the system (to the right). Postconditions should focus on what is the goal of each use case. Login and Logout use cases can be combined. Also try to keep all your use cases consistent.

**Comment by mcmurrym14** [comment]
Reviewed and revised UC4 per instructor feedback.
