### ISSUE TITLE
MS2 Review - Email Reports Use case

### ISSUE THREAD

**Issue by webbja15** [F18MIS4173Team5/Team5#49]
Normal course needs more detail. Alternative courses are incorrect. Exceptions would be considered as alternative courses.

**Comment by webbja15** [comment]
Update - This use case has been determined to need replacement with a Generate Report / Load Report function.  Use Case Specification will need to be updated to reflect this.

**Comment by deleonj16** [comment]
Removing use case. Lo longer relevant.
